name: Validate Wrike or Azure link(s) in PR Body

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review, edited]
    branches:
      - devel
      - release/**
      - feature/**
jobs:
  check_url:
    env:
      WRIKE_REGEX: "\\(https:\\|\\)//\\(www\\.\\|\\)wrike\\.com/open.htm?id=[[:digit:]]\\+"
      AZURE_REGEX: "AB#[[:digit:]]\\+"
      PR_BODY: "${{ github.event.pull_request.body }}"
    runs-on: ubuntu-latest
    steps:
      - name: Check for Wrike or Azure link in PR body
        run: |
          if ! echo "${{ env.PR_BODY }}" | grep -e "${{ env.WRIKE_REGEX }}" -e "${{ env.AZURE_REGEX }}" ; then
            echo "Error: Neither a Wrike link nor an Azure code found in the PR body. Please add a Wrike link or an Azure code (AB#<task_number>)."
            exit 1
          fi
          echo "::notice::Valid Wrike or Azure link found in PR body."